# Generated by Django 3.2.11 on 2022-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created'], 'verbose_name_plural': 'notes'},
        ),
        migrations.AlterField(
            model_name='note',
            name='memo',
            field=models.TextField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
