# Generated by Django 3.2.11 on 2022-01-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='done',
            new_name='complete',
        ),
        migrations.RemoveField(
            model_name='note',
            name='datecompleted',
        ),
    ]
