# Generated by Django 3.2.11 on 2022-01-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_auto_20220127_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
