# Generated by Django 3.2.11 on 2022-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_auto_20220526_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='False', max_length=30),
        ),
    ]
