# Generated by Django 3.2.11 on 2022-05-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='memo',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
